### ISSUE TITLE
Design Database Schema

### ISSUE THREAD

**Issue by jtdroste** [achievelife/backend#1]
Possible Table List:
- activities
  - List of activities available.  Has a point value associated with it, as well a required XP level
  - Columns
    - id
    - name
    - point
    - required_xp
- locations (coord)
  - Columns
    - id
    - name
    - lat
    - lng
- users
  - Columns
    - id
    - username
    - create_date
    - password
- sessions
  - Columns
    - id
    - user_id
    - create_date
    - fingerprint
- scores
  - Columns
    - id
    - activity_id
    - completed_date
- friends
  - Columns
    - id
    - user_id
    - friend_id
    - added_date

**Comment by jtdrostework** [comment]
This has been completed.  Waiting a further commit that makes this code.

**Comment by jtdroste** [comment]
Further commit will happen in `feature/sqlalchemy_models`, which will be sprint 3.

Database tables have been created in the server's MySQL DB.  Moving to Spring 3 milestone

**Comment by jtdroste** [comment]
Completed in 798e492519f7705333473940f65e60fc66cd744a.

CLOSED 🎉
